// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBysLCjSo3eiXik-89DoqMPPioXdaEOTIE',
    appId: '1:986217921353:web:0e5c8ee6387eb31f1b3898',
    messagingSenderId: '986217921353',
    projectId: 'nav-guinee',
    authDomain: 'nav-guinee.firebaseapp.com',
    storageBucket: 'nav-guinee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTVwPE56enA--fapNVtPrmgobsKzX1Brk',
    appId: '1:986217921353:android:6ee97e9445c9a7c31b3898',
    messagingSenderId: '986217921353',
    projectId: 'nav-guinee',
    storageBucket: 'nav-guinee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjdTBLbSOUiYfgaW7Spay-Pf-5usFBoFU',
    appId: '1:986217921353:ios:411ded7153d7bf181b3898',
    messagingSenderId: '986217921353',
    projectId: 'nav-guinee',
    storageBucket: 'nav-guinee.firebasestorage.app',
    iosClientId: '986217921353-up96q45a8o8ff2dre2l8l7gkdl4iah00.apps.googleusercontent.com',
    iosBundleId: 'com.domain.safeGuinee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjdTBLbSOUiYfgaW7Spay-Pf-5usFBoFU',
    appId: '1:986217921353:ios:411ded7153d7bf181b3898',
    messagingSenderId: '986217921353',
    projectId: 'nav-guinee',
    storageBucket: 'nav-guinee.firebasestorage.app',
    iosClientId: '986217921353-up96q45a8o8ff2dre2l8l7gkdl4iah00.apps.googleusercontent.com',
    iosBundleId: 'com.domain.safeGuinee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBysLCjSo3eiXik-89DoqMPPioXdaEOTIE',
    appId: '1:986217921353:web:bf88b3388822b8a61b3898',
    messagingSenderId: '986217921353',
    projectId: 'nav-guinee',
    authDomain: 'nav-guinee.firebaseapp.com',
    storageBucket: 'nav-guinee.firebasestorage.app',
  );
}
